# Generated by Django 5.2.11 on 2026-02-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('extracting', 'extracting'), ('parsed', 'parsed'), ('failed', 'failed')], default='uploaded', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
