# Generated by Django 5.2.11 on 2026-02-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='jobs.jobdescription')),
                ('resumes', models.ManyToManyField(related_name='batches', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='RankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.TextField(blank=True)),
                ('missing_required', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('candidate_suggestions', models.JSONField(blank=True, default=list)),
                ('model_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ranking.rankingbatch')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='resumes.resume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'job', 'resume'), name='uniq_result_per_batch')],
            },
        ),
    ]
